version: '3'

services:
  
  mongodb-unimodeler:
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123
    ports:
      - 27017:27017
    volumes:
      - ./docker/mongodb:/dumps



